-- Active: 1676656133940@@127.0.0.1@3306@exchange_bot

CREATE DATABASE nilo;

USE nilo;

DROP TABLE CONFIGS;

CREATE TABLE
    `CONFIGS` (
        `id` INT AUTO_INCREMENT,
        `name` VARCHAR(10),
        `os` VARCHAR(10),
        `when` TIMESTAMP DEFAULT CURRENT_DATE,
        `expire` TIMESTAMP DEFAULT DATE_ADD(CURRENT_DATE, INTERVAL + 1 MONTH),
        `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (id)
    );

SELECT * FROM USER;